configMap:
  LANGFLOW_DATABASE_URL: "postgresql://<USER>:<PASSWORD>@127.0.0.1:5432/<DB_NAME>"
  LANGFLOW_AUTO_LOGIN: "true"
  LANGFLOW_SUPERUSER: "admin"
  LANGFLOW_SUPERUSER_PASSWORD: "<superuser-password>"
  LANGFLOW_SECRET_KEY: "<random-secret-key>"
  LANGFLOW_NEW_USER_IS_ACTIVE: "true"
  LANGFLOW_CACHE_TYPE: "memory"
  LANGFLOW_LOG_LEVEL: "info"

image:
  tag: "latest"

INGRESS:
  ENABLE: true
  HOSTS:
    - HOST: "langflow-staging.example.com"

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "250m"
    memory: "512Mi" 