apiVersion: v1
kind: ServiceAccount
metadata:
  name: langflow-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: github-actions-sa@arctic-moon-463710-t0.iam.gserviceaccount.com 